services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2    # Maps the logs directory
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: eve_online
      MYSQL_USER: eve_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
