services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: eve_online
      MYSQL_USER: eve_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql

  php-apache:
    build: .  # Specify build context for Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
