services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: eve_online
      MYSQL_USER: eve_user
      MYSQL_PASSWORD: your_password  # Your actual password
    volumes:
      - db_data:/var/lib/mysql

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
